src/Entity/Singer.php
<?php

namespace App\Entity;

use App\Repository\SingerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\Timestampable;

/**
 * @ORM\Entity(repositoryClass=SingerRepository::class)
 * 
 * 
 * @ORM\HasLifecycleCallbacks()
 */
class Singer
{
    use Timestampable;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\OneToMany(targetEntity=Song::class, mappedBy="singer")
     */
    private $songs;

    /**
     * @ORM\Column(type="text")
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    public function __construct()
    {
        $this->songs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return Collection<int, Song>
     */
    public function getSongs(): Collection
    {
        return $this->songs;
    }

    public function addSong(Song $song): self
    {
        if (!$this->songs->contains($song)) {
            $this->songs[] = $song;
            $song->setSinger($this);
        }

        return $this;
    }

    public function removeSong(Song $song): self
    {
        if ($this->songs->removeElement($song)) {
            // set the owning side to null (unless already changed)
            if ($song->getSinger() === $this) {
                $song->setSinger(null);
            }
        }

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getFullName(): string
    {
        return $this->getFirstname().' '.$this->getLastname();
    }

    public function __toString()
    {
        return $this->getFullName();
    }

}

src/Entity/Song.php
<?php

namespace App\Entity;

use App\Repository\SongRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\Timestampable;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=SongRepository::class)
 * 
 * 
 * @ORM\HasLifecycleCallbacks()
 */
class Song
{
    use Timestampable;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * 
     * @Assert\NotBlank()
     */
    private $Title;

    /**
     * @ORM\ManyToOne(targetEntity=Singer::class, inversedBy="songs")
     * 
     * @Assert\NotBlank()
     */
    private $singer;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $release_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getSinger(): ?Singer
    {
        return $this->singer;
    }

    public function setSinger(?Singer $singer): self
    {
        $this->singer = $singer;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeImmutable
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeImmutable $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }
}

src/Controller/SongController.php
<?php

namespace App\Controller;

use App\Entity\SongSearch;
use App\Form\SongSearchType;
use App\Repository\SongRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SongController extends AbstractController
{
    private $songRepository;

    public function __construct(SongRepository $songRepository)
    {
        $this->songRepository = $songRepository;
    }
    /**
     * @Route("/song", name="app_song")
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {

        $songSearch = new SongSearch();
        $serachForm = $this->createForm(SongSearchType::class, $songSearch);

        $serachForm->handleRequest($request);
        $songs = $paginator->paginate(
            $this->songRepository->findSongs($songSearch),
            $request->query->getInt('page', 1), 9);
            
        return $this->render('song/index.html.twig', [
            'songs'      => $songs,
            'searchForm' => $serachForm->createView()
        ]);
    }
}

templates/song/_list_song.html.twig
<div class="col-md-4 mb-4">
    <div class="card">
        <img class="w-50 align-self-center" src="{{ asset('images/song/song.jpg') }}" alt="{{ song.title }} ">
        <div class="card-body">
            <h5 class="card-title text-muted">{{ song.title}}</h5>
            <p class="card-text"><small class="text-muted">A/C: </small>{{ song.singer.fullName }}</p>
            <p class="card-text"><small class="text-muted">Réalisé le: </small>{{ song.releaseDate|date("m/d/Y") }}</p>
        </div>    
    </div>
</div>

templates/song/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SongController!{% endblock %}

{% block body %}
    <div class="jumbotron">
        {{ form_start( searchForm ) }}
            <div class="form-row align-items-end">
                <div class="col">
                    <div class="form-group">
                        {{ form_row(searchForm.title, 
                        {
                            'attr': {
                                'class': 'form-control'
                            }}) 
                        }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        {{ form_row(searchForm.singer, {
                            'attr': {
                                'class': 'form-control'
                            }}) }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-small btn-block">Rechercher</button>
                    </div>
                </div>
            </div>
        {{ form_end( searchForm ) }}
    </div>
    <h1 class="m-4 text-center text-success">Liste des chansons</h1>
    <div class="row">
        {% if songs|length > 0 %}
            {% for song in songs %}
               {{ include('song/_list_song.html.twig') }}
            {% endfor %}
        {% endif %}
    <div>
    <div class="row">
        <div class="pagination">
            {{ knp_pagination_render(songs) }}
        </div>
    </div>
{% endblock %}